-- Catálogo: Máquinas
CREATE TABLE machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    acquisition_cost NUMERIC(19, 4) NOT NULL CHECK (acquisition_cost >= 0),
    useful_life_hours NUMERIC(19, 4) NOT NULL CHECK (useful_life_hours > 0),
    power_watts NUMERIC(19, 4) NOT NULL CHECK (power_watts >= 0),
    maintenance_cost_per_hour NUMERIC(19, 4) NOT NULL CHECK (maintenance_cost_per_hour >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Catálogo: Materiales
CREATE TABLE materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    purchase_price NUMERIC(19, 4) NOT NULL CHECK (purchase_price >= 0),
    quantity NUMERIC(19, 4) NOT NULL CHECK (quantity >= 0),
    unit VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Catálogo: Herramientas
CREATE TABLE tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    acquisition_cost NUMERIC(19, 4) NOT NULL CHECK (acquisition_cost >= 0),
    estimated_uses NUMERIC(19, 4) NOT NULL CHECK (estimated_uses > 0),
    maintenance_percentage NUMERIC(5, 2) NOT NULL CHECK (maintenance_percentage >= 0 AND maintenance_percentage <= 100),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

-- Trabajo: Proyectos
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Relación: Proyecto - Máquinas
CREATE TABLE project_machines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    machine_id BIGINT NOT NULL REFERENCES machines(id),
    estimated_hours NUMERIC(19, 4) NOT NULL CHECK (estimated_hours >= 0)
);

-- Relación: Proyecto - Materiales
CREATE TABLE project_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    material_id BIGINT NOT NULL REFERENCES materials(id),
    quantity_used NUMERIC(19, 4) NOT NULL CHECK (quantity_used >= 0)
);

-- Relación: Proyecto - Herramientas
CREATE TABLE project_tools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    tool_id BIGINT NOT NULL REFERENCES tools(id),
    uses NUMERIC(19, 4) NOT NULL CHECK (uses >= 0)
);

-- Presupuesto: Quotes
CREATE TABLE quotes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES projects(id),
    margin_percentage NUMERIC(5, 2) NOT NULL CHECK (margin_percentage >= 0),
    safety_percentage NUMERIC(5, 2) NOT NULL CHECK (safety_percentage >= 0),
    base_cost NUMERIC(19, 4) NOT NULL CHECK (base_cost >= 0),
    adjusted_cost NUMERIC(19, 4) NOT NULL CHECK (adjusted_cost >= 0),
    final_price NUMERIC(19, 4) NOT NULL CHECK (final_price >= 0),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
